local p = require("retro82.palette")

return {
  ["DiagnosticDeprecated"] = { fg = "NONE", bg = "NONE", sp = p.orange, strikethrough = true },
  ["DiagnosticError"] = { fg = p.red, bg = "NONE", sp = "NONE" },
  ["DiagnosticHintFloating"] = { fg = p.teal, bg = "NONE", sp = "NONE" },
  ["DiagnosticHint"] = { fg = p.cyan, bg = "NONE", sp = "NONE" },
  ["DiagnosticInfo"] = { fg = p.cyan, bg = "NONE", sp = "NONE" },
  ["DiagnosticOk"] = { fg = p.teal, bg = "NONE", sp = "NONE" },
  ["DiagnosticSignError"] = { fg = p.red, bg = p.bg1, sp = "NONE" },
  ["DiagnosticSignHint"] = { fg = p.cyan, bg = p.bg1, sp = "NONE" },
  ["DiagnosticSignInfo"] = { fg = p.teal, bg = p.bg1, sp = "NONE" },
  ["DiagnosticSignWarn"] = { fg = p.orange, bg = p.bg1, sp = "NONE" },
  ["DiagnosticUnderlineError"] = { fg = "NONE", bg = "NONE", sp = p.red, undercurl = true },
  ["DiagnosticUnderlineHint"] = { fg = "NONE", bg = "NONE", sp = p.teal, undercurl = true },
  ["DiagnosticUnderlineInfo"] = { fg = "NONE", bg = "NONE", sp = p.cyan, undercurl = true },
  ["DiagnosticUnderlineOk"] = { fg = "NONE", bg = "NONE", sp = p.teal, undercurl = true },
  ["DiagnosticUnderlineWarn"] = { fg = "NONE", bg = "NONE", sp = p.orange, undercurl = true },
  ["DiagnosticUnnecessary"] = { fg = p.muted, bg = "NONE", sp = "NONE", underline = true },
  ["DiagnosticVirtualTextError"] = { fg = p.red, bg = p.bg1, sp = "NONE", bold = true },
  ["DiagnosticVirtualTextHint"] = { fg = p.teal, bg = p.bg1, sp = "NONE" },
  ["DiagnosticVirtualTextInfo"] = { fg = p.cyan, bg = p.bg1, sp = "NONE" },
  ["DiagnosticVirtualTextWarn"] = { fg = p.orange, bg = p.bg1, sp = "NONE", bold = true },
  ["DiagnosticVirtualTextWarning"] = { fg = p.fg0, bg = p.bg1, sp = "NONE" },
  ["DiagnosticWarn"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["DiagnosticWarningFloating"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["DiagnosticWarning"] = { fg = p.red, bg = "NONE", sp = "NONE" },
  ["DiagnosticErrorFloating"] = { link = "DiagnosticError" },
  ["DiagnosticFloatingError"] = { link = "DiagnosticError" },
  ["DiagnosticFloatingHint"] = { link = "DiagnosticHint" },
  ["DiagnosticFloatingInfo"] = { link = "DiagnosticInfo" },
  ["DiagnosticFloatingOk"] = { link = "DiagnosticOk" },
  ["DiagnosticFloatingWarn"] = { link = "DiagnosticWarn" },
  ["DiagnosticFloatingWarning"] = { link = "DiagnosticWarning" },
  ["DiagnosticSignOk"] = { link = "DiagnosticOk" },
  ["DiagnosticVirtualTextOk"] = { link = "DiagnosticOk" },
  ["LspCodeLens"] = { link = "Comment" },
  ["@lsp.type.comment"] = { link = "Comment" },
  ["@lsp.type.decorator"] = { link = "Function" },
  ["@lsp.type.function"] = { link = "Function" },
  ["@lsp.type.method"] = { link = "Function" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@variable.member" },
  ["@lsp.type.type"] = { link = "Type" },
  ["@lsp.type.variable"] = { link = "Identifier" },
  ["@lsp.mod.defaultLibrary"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["@lsp.type.namespace.lua"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["@lsp.type.parameter.lua"] = { link = "Identifier" },
  ["@lsp.type.property.lua"] = { link = "@variable.member" },
  ["@lsp.type.variable.lua"] = { link = "Identifier" },
  ["@lsp.typemod.variable.defaultLibrary.lua"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.function.defaultLibrary.lua"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.method.defaultLibrary.lua"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.property.defaultLibrary.lua"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["@lsp.type.enumMember"] = { fg = p.amber, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.function.builtin"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["@lsp.typemod.function.defaultLibrary"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["LspBorderBG"] = { fg = p.orange, bg = p.bg0, sp = "NONE" },
  ["LspInlayHint"] = { fg = p.muted, bg = "NONE", sp = "NONE", italic = true },
  ["LspFloatWinNormal"] = { fg = p.fg0, bg = p.bg0, sp = "NONE" },
  ["LspReferenceRead"] = { fg = p.cyan, bg = "NONE", sp = p.red, bold = true, undercurl = true },
  ["LspReferenceText"] = { fg = p.fg0, bg = p.bg2, sp = p.red, bold = true, undercurl = true },
  ["LspReferenceWrite"] = { fg = p.cyan, bg = "NONE", sp = p.red, bold = true, undercurl = true },
  ["LspSignatureActiveParameter"] = { fg = "NONE", bg = "NONE", sp = p.fg1, bold = true, italic = true, underline = true },
}
