local p = require("retro82.palette")

return {
  ["@boolean"] = { link = "Boolean" },
  ["@comment"] = { link = "Comment" },
  ["@constant.builtin"] = { link = "Special" },
  ["@constant"] = { link = "Constant" },
  ["@constructor"] = { link = "Special" },
  ["@field"] = { link = "@variable.member" },
  ["@function.builtin"] = { link = "Special" },
  ["@function"] = { link = "Function" },
  ["@keyword"] = { link = "Keyword" },
  ["@method"] = { link = "Function" },
  ["@namespace"] = { link = "@module" },
  ["@number"] = { link = "Number" },
  ["@parameter"] = { link = "@variable.parameter" },
  ["@preproc"] = { link = "PreProc" },
  ["@property"] = { link = "@variable.member" },
  ["@punctuation"] = { link = "Delimiter" },
  ["@string"] = { link = "String" },
  ["@text.diff.add"] = { link = "DiffAdd" },
  ["@text.diff.delete"] = { link = "DiffDelete" },
  ["@text.literal"] = { link = "Comment" },
  ["@text.reference"] = { link = "Identifier" },
  ["@text.title"] = { link = "Title" },
  ["@text.todo"] = { link = "Todo" },
  ["@text.underline"] = { link = "Underlined" },
  ["@text.uri"] = { link = "Underlined" },
  ["@type"] = { link = "Type" },
  ["@variable"] = { link = "Identifier" },
  ["@attribute"] = { fg = p.preproc, bg = "NONE", sp = "NONE" },
  ["@character"] = { fg = p.amber, bg = "NONE", sp = "NONE" },
  ["@character.special"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["@comment.documentation"] = { fg = p.muted, bg = "NONE", sp = "NONE", italic = true },
  ["@comment.error"] = { fg = p.bg0, bg = p.red, sp = "NONE", bold = true },
  ["@comment.hint"] = { fg = p.bg0, bg = p.teal, sp = "NONE", bold = true },
  ["@comment.note"] = { fg = p.bg0, bg = p.cyan, sp = "NONE", bold = true },
  ["@comment.todo"] = { fg = p.bg0, bg = p.amber, sp = "NONE", bold = true },
  ["@comment.warning"] = { fg = p.bg0, bg = p.orange, sp = "NONE", bold = true },
  ["@constant.macro"] = { link = "PreProc" },
  ["@constructor.lua"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["@diff.delta"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["@diff.minus"] = { fg = p.red, bg = "NONE", sp = "NONE" },
  ["@diff.plus"] = { fg = p.cyan, bg = "NONE", sp = "NONE" },
  ["@function.call"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["@function.macro"] = { link = "PreProc" },
  ["@function.method"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["@function.method.call"] = { fg = p.func, bg = "NONE", sp = "NONE" },
  ["@keyword.conditional"] = { fg = p.cyan, bg = "NONE", sp = "NONE", bold = true },
  ["@keyword.conditional.ternary"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["@keyword.coroutine"] = { fg = p.cyan, bg = "NONE", sp = "NONE", bold = true },
  ["@keyword.debug"] = { fg = p.red, bg = "NONE", sp = "NONE", bold = true },
  ["@keyword.directive"] = { link = "PreProc" },
  ["@keyword.directive.define"] = { fg = p.preproc, bg = "NONE", sp = "NONE", bold = true },
  ["@keyword.exception"] = { fg = p.red, bg = "NONE", sp = "NONE", bold = true },
  ["@keyword.function"] = { fg = p.cyan, bg = "NONE", sp = "NONE", bold = true },
  ["@keyword.import"] = { link = "PreProc" },
  ["@keyword.modifier"] = { fg = p.cyan, bg = "NONE", sp = "NONE" },
  ["@keyword.operator"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["@keyword.repeat"] = { fg = p.cyan, bg = "NONE", sp = "NONE", bold = true },
  ["@keyword.return"] = { fg = p.cyan, bg = "NONE", sp = "NONE", bold = true },
  ["@keyword.type"] = { fg = p.teal, bg = "NONE", sp = "NONE", bold = true },
  ["@markup"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["@markup.heading"] = { fg = p.red, bg = "NONE", sp = "NONE", bold = true },
  ["@markup.heading.1.markdown"] = { fg = p.red, bg = "NONE", sp = "NONE", bold = true },
  ["@markup.heading.2.markdown"] = { fg = p.orange, bg = "NONE", sp = "NONE", bold = true },
  ["@markup.heading.3.markdown"] = { fg = p.amber, bg = "NONE", sp = "NONE", bold = true },
  ["@markup.heading.4.markdown"] = { fg = p.teal, bg = "NONE", sp = "NONE", bold = true },
  ["@markup.heading.5.markdown"] = { fg = p.cyan, bg = "NONE", sp = "NONE", bold = true },
  ["@markup.heading.6.markdown"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["@markup.italic"] = { fg = p.fg0, bg = "NONE", sp = "NONE", italic = true },
  ["@markup.link"] = { fg = p.teal, bg = "NONE", sp = "NONE", underline = true },
  ["@markup.link.label"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["@markup.link.url"] = { fg = p.cyan, bg = "NONE", sp = "NONE", underline = true },
  ["@markup.list"] = { fg = p.cyan, bg = "NONE", sp = "NONE" },
  ["@markup.list.checked"] = { fg = p.teal, bg = "NONE", sp = "NONE", bold = true },
  ["@markup.list.unchecked"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["@markup.math"] = { fg = p.amber, bg = "NONE", sp = "NONE" },
  ["@markup.quote"] = { fg = p.muted, bg = "NONE", sp = "NONE", italic = true },
  ["@markup.raw"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["@markup.strikethrough"] = { fg = p.muted, bg = "NONE", sp = "NONE", strikethrough = true },
  ["@markup.strong"] = { fg = p.fg0, bg = "NONE", sp = "NONE", bold = true },
  ["@module"] = { fg = p.module, bg = "NONE", sp = "NONE", italic = true },
  ["@number.float"] = { fg = p.number, bg = "NONE", sp = "NONE" },
  ["@operator"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["@property.css"] = { fg = p.cyan, bg = "NONE", sp = "NONE" },
  ["@property.scss"] = { fg = p.cyan, bg = "NONE", sp = "NONE" },
  ["@punctuation.bracket"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["@punctuation.delimiter"] = { fg = p.fg0, bg = "NONE", sp = "NONE" },
  ["@punctuation.special"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["@string.documentation"] = { fg = p.amber, bg = "NONE", sp = "NONE", italic = true },
  ["@string.escape"] = { fg = p.red, bg = "NONE", sp = "NONE" },
  ["@string.regexp"] = { fg = p.cyan, bg = "NONE", sp = "NONE" },
  ["@string.special"] = { fg = p.orange, bg = "NONE", sp = "NONE" },
  ["@string.special.path"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["@string.special.symbol"] = { fg = p.amber, bg = "NONE", sp = "NONE" },
  ["@string.special.url"] = { fg = p.cyan, bg = "NONE", sp = "NONE", underline = true },
  ["@tag"] = { fg = p.module, bg = "NONE", sp = "NONE" },
  ["@tag.attribute"] = { fg = p.cyan, bg = "NONE", sp = "NONE", italic = true },
  ["@tag.builtin"] = { fg = p.teal, bg = "NONE", sp = "NONE", bold = true },
  ["@tag.delimiter"] = { fg = p.muted, bg = "NONE", sp = "NONE" },
  ["@type.builtin"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["@type.definition"] = { fg = p.type, bg = "NONE", sp = "NONE", bold = true },
  ["@variable.builtin"] = { fg = p.red, bg = "NONE", sp = "NONE", italic = true },
  ["@variable.member"] = { fg = p.member, bg = "NONE", sp = "NONE" },
  ["@variable.parameter"] = { fg = p.parameter, bg = "NONE", sp = "NONE" },
}
